title: "AstroTaca"
description: "Astrophotography gear, guides, and blog."
baseurl: "" 
url: "https://astrotaca.github.io"
theme: minima # You can change this later if needed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap