title: "AstroTaca"
description: "Astrophotography gear, guides, and blog."
baseurl: "" 
url: "https://astrotaca.github.io"

# Force GitHub Pages to use the correct theme
remote_theme: jekyll/minima

# Enable Jekyll plugins (required for Minima)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
