title: "AstroTaca"
description: "Astrophotography Gear & Guides"
baseurl: ""
url: "http://127.0.0.1:4000"

# Blog posts => /blog/my-title/
permalink: /blog/:title/

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - yarn.lock

feed:
  path: feed
future: true
