- title: "AstroTaca Flap Flat Panel"
  url: "/products/flap-flat-panel/"
  image: "/assets/images/flap-flat-panel.jpg"
  description: "$200.00 — Reliable flat panel for your flats."
- title: "AstroTaca Electronic Auto Focuser"
  url: "/products/eaf/"
  image: "/assets/images/eaf.jpg"
  description: "$100.00 — Automated focusing for clear stars."
- title: "AstroTaca DC Hub"
  url: "/products/dc-hub/"
  image: "/assets/images/dc-hub.jpg"
  description: "$50.00 — Manage power distribution easily."
- title: "Processing Stars with StarNet2 in PixInsight"
  url: "/guides/starnet2-processing-guide/"
  image: "/assets/images/starnet2processingguide.jpg"
  description: "Processing the stars in your images with StarNet2."